### ISSUE TITLE
Ferramentas OpenSource para compor a solução CTEDS

### ISSUE THREAD

**Issue by ferdinandocastilho** [ferdinandocastilho/selecao-cteds#16]
# Description

Buscar soluções open-source que possam ser agregadas para componetizar a plataforma CTEDS.

# Task

- [ ] Formulário
- [ ] Comunicação por Áudio e Vídeo
- [ ] IDE para testes com possibilidade de análise de resultado
- [ ] Cadastro de Perguntas e Respostas pré-definidas (múltiplas escolhas e dissertativas)
