### ISSUE TITLE
Criar Roadmap no Readme

### ISSUE THREAD

**Issue by ferdinandocastilho** [ferdinandocastilho/selecao-cteds#17]
# Description 

Criar um roadmap com os componentes da solução e adicionar ao readme

# Task

- [ ] Login
- [ ] Formulário
- [ ] Componente IDE para o teste
- [ ] Integração com o Chat de voz e vídeo
- [ ] Fórum
- [ ] Ambiente de Avaliação
- [ ] Drive de Arquivos
