### ISSUE TITLE
Criar protótipo

### ISSUE THREAD

**Issue by GabrielaProvedel** [ferdinandocastilho/selecao-cteds#6]
### Description ###

Criar protótipo com fluxo de usuário e desenhar telas com base nas funcionalidades pré-estabelecidas.

### Tasks ###

- [x] Definir fluxo de usuário
- [x] Desenhar telas do protótipo de baixa fidelidade
- [x] Revisar protótipo de baixa fidelidade
- [x] Completar as informações do protótipo
- [x] Revisar documento completo

### Acceptance Criteria ###

Protótipo desenvolvido e revisado

### Complexity ###

https://planningpokeronline.com/

**Comment by GabrielaProvedel** [comment]
[Protótipo.pdf](https://github.com/ferdinandocastilho/selecao-cteds/files/9285346/Prototipo.pdf)
